### ISSUE TITLE
Совместимость с D7

### ISSUE THREAD

**Issue by AndrewDelarge** [anmaslov/peshkariki#1]
В данный момент используя метод D7 - Delivery\Services\Manager::getRestrictedObjectsList() нет возможности получить доставку, тк этот метод обращается к новой таблице. 
Было бы замечательно если бы у модуля была совместимость с новым ядром.

**Comment by anmaslov** [comment]
Проверил, у меня работает!

Возможно, передаете LOCATION_TO - пустой.
Покажите пожалуйста весь код вызова.
